#ifndef __FLIGHT_CONTROL_H
#define __FLIGHT_CONTROL_H

#include "stm32f10x.h"
//#include "modules_flight_input.h"
#include "modules_flight_status.h"


#ifdef __cplusplus
extern "C" {
#endif

/*==============================================================================
 * Type Definitions
 *============================================================================*/

/**
 * @brief Flight control output structure.
 *
 * @details
 * This structure contains the attitude controller outputs
 * generated by the flight control algorithm.
 *
 * These outputs are typically mixed into motor commands
 * by the motor mixer module.
 */
typedef struct
{
    float roll_out;     // Roll axis control output
    float pitch_out;    // Pitch axis control output
    float yaw_out;      // Yaw axis control output
} ControlOutput_t;

/*==============================================================================
 * Public Function Prototypes
 *============================================================================*/
// void FlightControl_Reset(void);

// void FlightControl_Update(const _st_Mpu *mpu,
//                           const _st_AngE *angle,
//                           const FlightCommand_t *cmd,
//                           FlightState_t state,
//                           float dt,
//                           ControlOutput_t *out);


/* 初始化控制器 */
void FlightControl_Init(void);

/* 重置控制器内部状态 */
void FlightControl_Reset(void);

/* 单步控制更新 */
void FlightControl_Update(const _st_Mpu *mpu,
                          const _st_AngE *angle,
                          const FlightCommand_t *cmd,
                          FlightState_t state,
                          float dt,
                          ControlOutput_t *out);

#ifdef __cplusplus
}
#endif

#endif /* __FLIGHT_CONTROL_H */